export const backgroundImageObject = {
	'blackboard_harin.jpg': require('../../assets/images/background/blackboard_harin.jpg'),
	'blackboard_seoyeon.jpg': require('../../assets/images/background/blackboard_seoyeon.jpg'),
	'cafe.jpg': require('../../assets/images/background/cafe.jpg'),
	'cafeteria.jpg': require('../../assets/images/background/cafeteria.jpg'),
	'chicken.jpg': require('../../assets/images/background/chicken.jpg'),
	'city.jpg': require('../../assets/images/background/city.jpg'),
	'classroom_signboard.jpg': require('../../assets/images/background/classroom_signboard.jpg'),
	'classroom.jpg': require('../../assets/images/background/classroom.jpg'),
	'entrance.jpg': require('../../assets/images/background/entrance.jpg'),
	'entrance_rounge1.jpg': require('../../assets/images/background/entrance_rounge1.jpg'),
	'entrance_rounge2.jpg': require('../../assets/images/background/entrance_rounge2.jpg'),
	'goose.jpg': require('../../assets/images/background/goose.jpg'),
	'kakak_talk.png': require('../../assets/images/background/kakak_talk.png'),
	'middle_rounge.jpg': require('../../assets/images/background/middle_rounge.jpg'),
	'movie.jpg': require('../../assets/images/background/movie.jpg'),
	'night_light1.jpg': require('../../assets/images/background/night_light1.jpg'),
	'night_light2.jpg': require('../../assets/images/background/night_light2.jpg'),
	'passageway.jpg': require('../../assets/images/background/passageway.jpg'),
	'river1.jpg': require('../../assets/images/background/river1.jpg'),
	'river2.jpg': require('../../assets/images/background/river2.jpg'),
	'street.jpg': require('../../assets/images/background/street.jpg'),
	'sungsimdang.jpg': require('../../assets/images/background/sungsimdang.jpg'),
}
export const characterImageObject = {
	'harin_angry.png': require('../../assets/images/character/harin_angry.png'),
	'harin_back.png': require('../../assets/images/character/harin_back.png'),
	'harin_basic.png': require('../../assets/images/character/harin_basic.png'),
	'harin_detail.png': require('../../assets/images/character/harin_detail.png'),
	'harin_embarrass.png': require('../../assets/images/character/harin_embarrass.png'),
	'harin_half_back.png': require('../../assets/images/character/harin_half_back.png'),
	'harin_home.png': require('../../assets/images/character/harin_home.png'),
	'harin_shame.png': require('../../assets/images/character/harin_shame.png'),
	'harin_side.png': require('../../assets/images/character/harin_side.png'),
	'harin_smile.png': require('../../assets/images/character/harin_smile.png'),
	'harin_upset.png': require('../../assets/images/character/harin_upset.png'),
	'hero_detail.png': require('../../assets/images/character/hero_detail.png'),
	'hero_basic.png': require('../../assets/images/character/hero_basic.png'),
	'jinseop_basic.png': require('../../assets/images/character/jinseop_basic.png'),
	'jinseop_detail.png': require('../../assets/images/character/jinseop_detail.png'),
	'nubzuki_basic.PNG': require('../../assets/images/character/nubzuki_basic.PNG'),
	'nubzuki_detail.png': require('../../assets/images/character/nubzuki_detail.png'),
	'jihoo_basic.png': require('../../assets/images/character/jihoo_basic.png'),
	'jihoo_detail.png': require('../../assets/images/character/jihoo_detail.png'),
	'seoyeon_angry.png': require('../../assets/images/character/seoyeon_angry.png'),
	'seoyeon_back.png': require('../../assets/images/character/seoyeon_back.png'),
	'seoyeon_basic.png': require('../../assets/images/character/seoyeon_basic.png'),
	'seoyeon_detail.png': require('../../assets/images/character/seoyeon_detail.png'),
	'seoyeon_embarrass.png': require('../../assets/images/character/seoyeon_embarrass.png'),
	'seoyeon_home.png': require('../../assets/images/character/seoyeon_home.png'),
	'seoyeon_lighit_smile.png': require('../../assets/images/character/seoyeon_lighit_smile.png'),
	'seoyeon_shame.png': require('../../assets/images/character/seoyeon_shame.png'),
	'seoyeon_side.png': require('../../assets/images/character/seoyeon_side.png'),
	'seoyeon_smile.png': require('../../assets/images/character/seoyeon_smile.png'),
}
export const characterHeadImageObject = {
	'harin_head.png': require('../../assets/images/head/harin_head.png'),
	'hero_head.png': require('../../assets/images/head/hero_head.png'),
	'jihoo_head.png': require('../../assets/images/head/jihoo_head.png'),
	'jinseop_head.png': require('../../assets/images/head/jinseop_head.png'),
	'nubzuki_head.png': require('../../assets/images/head/nubzuki_head.png'),
	'seoyeon_head.png': require('../../assets/images/head/seoyeon_head.png'),
}